package webtoons

import (
	"context"
	"fmt"
	"net/url"
	"regexp"
	"strings"

	"github.com/PuerkitoBio/goquery"

	"github.com/rickl/quire/backend/theme"
)

// The two names the chapter-list API uses for the two tiers. They are not the
// names the *site paths* use: a series at /{lang}/canvas/... is "canvas" to
// the API, and everything else is "webtoon". Keeping both vocabularies
// straight in one place is cheaper than discovering the mismatch from a 404.
const (
	apiKindWebtoon = "webtoon"
	apiKindCanvas  = canvasSegment
)

// seasonRE finds a season number in an episode title. The platform writes it
// several ways — "[Season 2]", "Season 2", "S2 " — and the bracketed form is by
// far the most common.
var seasonRE = regexp.MustCompile(`(?i)\[?\bseason\s*\.?\s*(\d+)`)

// lang is the site language segment, from the source's BCP-47 tag.
//
// The site's own segments are lower-case and mostly match the tag; the one
// that does not is a script-qualified variant, which it spells with a hyphen
// where BCP-47 uses a capital.
func (t *Theme) lang(s *theme.Source) string {
	l := strings.ToLower(strings.TrimSpace(s.Lang))
	if l == "" {
		return "en"
	}
	return l
}

// seriesPath turns a series ID into a request path. IDs are stored
// site-relative, query string included: the identifier *is* a query parameter
// here, so an ID without one is not a series.
func (t *Theme) seriesPath(id string) string {
	id = strings.TrimSpace(id)
	if strings.HasPrefix(id, "/") {
		return id
	}
	return "/" + strings.TrimPrefix(id, "/")
}

// chapterPath turns a chapter ID into a request path.
func (t *Theme) chapterPath(id string) string { return t.seriesPath(id) }

// seriesRef pulls the numeric series identifier and the API's name for its
// tier out of a series ID.
//
// Both of the site's own spellings of the parameter are accepted, because
// links generated by different surfaces of the platform disagree and a user
// pasting one should not have to know which they have.
func (t *Theme) seriesRef(id string) (titleNo, kind string, err error) {
	u, err := url.Parse(t.seriesPath(id))
	if err != nil {
		return "", "", fmt.Errorf("%q is not a series id: %w", id, err)
	}
	q := u.Query()
	titleNo = strings.TrimSpace(q.Get(titleNoParam))
	if titleNo == "" {
		titleNo = strings.TrimSpace(q.Get(titleNoParamAlt))
	}
	if titleNo == "" {
		return "", "", fmt.Errorf("%q carries no series number", id)
	}

	kind = apiKindWebtoon
	for _, seg := range strings.Split(strings.Trim(u.EscapedPath(), "/"), "/") {
		if strings.EqualFold(seg, canvasSegment) {
			kind = apiKindCanvas
			break
		}
	}
	return titleNo, kind, nil
}

// seriesID keeps only links that are a series listing, returning "" otherwise.
//
// A search page is full of navigation, tier tabs and promotional links; the
// series rows are the ones that end in the listing path *and* carry the
// identifier. Requiring both is what keeps a "view all" tab out of the
// results.
func (t *Theme) seriesID(s *theme.Source, href string) string {
	rel := t.relativeID(s, href)
	if rel == "" {
		return ""
	}
	u, err := url.Parse(rel)
	if err != nil {
		return ""
	}
	if !strings.HasSuffix(strings.TrimSuffix(u.EscapedPath(), "/"), "/list") {
		return ""
	}
	q := u.Query()
	if q.Get(titleNoParam) == "" && q.Get(titleNoParamAlt) == "" {
		return ""
	}
	return rel
}

// relativeID resolves href against the source base and returns the site path
// **with its query string**, or "" if it left the site.
//
// Keeping the query is not optional here as it is elsewhere: the series and
// episode identifiers are query parameters, so a path-only ID would name
// every series on the site at once.
//
// The host comparison accepts the mobile host as well as the configured one.
// The chapter-list API is served from it and its viewer links are absolute, so
// rejecting them would mean no chapters at all.
func (t *Theme) relativeID(s *theme.Source, href string) string {
	href = strings.TrimSpace(href)
	if href == "" {
		return ""
	}
	base, err := url.Parse(s.BaseURL)
	if err != nil {
		return ""
	}
	u, err := url.Parse(href)
	if err != nil {
		return ""
	}
	abs := base.ResolveReference(u)
	if !sameSite(abs.Hostname(), base.Hostname()) {
		return ""
	}
	out := abs.EscapedPath()
	if abs.RawQuery != "" {
		out += "?" + abs.RawQuery
	}
	return out
}

// sameSite reports whether host is the configured host or its mobile sibling.
func sameSite(host, base string) bool {
	if strings.EqualFold(host, base) {
		return true
	}
	return strings.EqualFold(host, mobileHost(base))
}

// mobileHost is the `m.` sibling of a host: the chapter-list API lives there
// and nowhere else.
//
// It stays under the same registrable domain as the configured base, so PLAN
// §7.4's boundary permits it without any AllowedHosts entry — the declaration
// this theme does make is for the image CDN, which is a genuinely different
// domain.
func mobileHost(host string) string {
	host = strings.ToLower(strings.TrimSpace(host))
	if host == "" {
		return ""
	}
	if strings.HasPrefix(host, "m.") {
		return host
	}
	return "m." + strings.TrimPrefix(host, "www.")
}

// mobileURL builds an absolute URL on the mobile host for a site-relative
// path.
func (t *Theme) mobileURL(s *theme.Source, path string) string {
	base, err := url.Parse(s.BaseURL)
	if err != nil {
		return ""
	}
	m := *base
	m.Host = mobileHost(base.Hostname())
	if p := base.Port(); p != "" {
		m.Host += ":" + p
	}
	m.Path, m.RawQuery, _ = strings.Cut(path, "?")
	return m.String()
}

// absolute resolves a possibly-relative URL against the source base.
func (t *Theme) absolute(s *theme.Source, ref string) string {
	if strings.TrimSpace(ref) == "" {
		return ""
	}
	abs, err := s.Resolve(ref)
	if err != nil {
		return ""
	}
	return abs
}

// get fetches a URL or path and returns the body.
//
// Everything this theme asks for is discovery in PLAN §7.4's sense: a search,
// a listing, a link being followed. The page *images* are retrieval, and they
// are fetched by the download queue rather than here.
func (t *Theme) get(ctx context.Context, s *theme.Source, ref string) (string, error) {
	p, err := s.Policy()
	if err != nil {
		return "", err
	}
	abs := ref
	if !strings.Contains(ref, "://") {
		if abs, err = s.Resolve(ref); err != nil {
			return "", fmt.Errorf("%s: resolve %s: %w", ID, ref, err)
		}
	}
	resp, err := t.f.Get(ctx, p, abs)
	if err != nil {
		return "", fmt.Errorf("%s: get %s: %w", ID, ref, err)
	}
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		return "", fmt.Errorf("%s: %s: HTTP %d", ID, ref, resp.StatusCode)
	}
	return string(resp.Body), nil
}

// doc fetches a path and parses it as HTML.
func (t *Theme) doc(ctx context.Context, s *theme.Source, path string) (*goquery.Document, error) {
	body, err := t.get(ctx, s, path)
	if err != nil {
		return nil, err
	}
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("%s: %s: parse HTML: %w", ID, path, err)
	}
	return doc, nil
}
